### ISSUE TITLE
Clarification Needed on Cloning Instructions

### ISSUE THREAD

**Issue by Dipec001** [Sohammhatre10/Cadmi_AI#17]
### Issue with Cloning Instructions in README

The current README suggests that users can clone the repository directly using the following command:

`git clone https://github.com/Sohammhatre10/Cadmi_AI.git`

However, since users do not have write access to the main repository, they should first fork the repository to their own account before cloning it. I recommend updating the instructions to clarify this process for future contributors.

### Suggested Update

1. **Fork the repository** using the GitHub interface.
2. **Clone your forked repository** using the following command:

`git clone https://github.com/your-username/Cadmi_AI.git`

3. Continue with the existing instructions as needed.
4. Also instructions on how to run the code too would great for contributors

Please assign this issue to me as I would like to work on updating the README.

Thank you for your attention to this matter!

**Comment by Dipec001** [comment]
@Sohammhatre10 please check this

**Comment by Sohammhatre10** [comment]
Yupp you may complete this but I guess such a change wont be acknowledged by Hacktoberfest maintainers @Dipec001
