### ISSUE TITLE
Create basic GUI for the landing page of Cadmi 

### ISSUE THREAD

**Issue by Sohammhatre10** [Sohammhatre10/Cadmi_AI#2]
Create basic UI for Cadmi and deliver a user-friendly experience for the same

Accepted stack would be - 

1. Django
2. MERN
3. HTML/JS/CSS
4. Flask
5. Streamlit UI

**Comment by SujitSakore** [comment]
Hello @Sohammhatre10  will you please assign me this one.

**Comment by Sohammhatre10** [comment]
Heyy @SujitSakore will assign this one
All the best!

**Comment by SujitSakore** [comment]
Hello @Sohammhatre10 I have resolved the issue. If there are any changes or further adjustments needed, please let me know. I would appreciate it if you could accept my pull request.

**Comment by Sohammhatre10** [comment]
@SujitSakore Add your changes in the webpages folder and then submit your PR

**Comment by SujitSakore** [comment]
Hello @Sohammhatre10, I have added my changes to the webpages folder as you suggested. If you need any further adjustments, please let me know. I would appreciate it if you could accept my pull request. Thank you!
