### ISSUE TITLE
Add a web-scraper for Delhi University's 2024 cutoff

### ISSUE THREAD

**Issue by Sohammhatre10** [Sohammhatre10/Cadmi_AI#3]
Requirements are -

1. A selenium bot for scraping Delhi University's 2024 cutoff data and automation for logging
2. Ease of use and clean code, add a doc string for everything

**Comment by SujitSakore** [comment]
Hello @Sohammhatre10  will you please assign me this one.

**Comment by gaurav-rm11** [comment]
assign me

**Comment by Sohammhatre10** [comment]
Will assign you this one too. All the best!

**Comment by Sohammhatre10** [comment]
@gaurav-rm11 any progress on this? If not will have to reassign this to someone else. Thanks!

**Comment by Dipec001** [comment]
Any update on it? I should be able to handle this

**Comment by pokymono** [comment]
Hey, I would like to add this feature, kindly assign this to me, thankyou!

**Comment by Sohammhatre10** [comment]
@Dipec001 and @Rishitshivam for this issue there are no updates from @gaurav-rm11's side so will be assigning you both this too. The PR that works will be accepted. Thanks!

**Comment by gaurav-rm11** [comment]
i am currently not able to work as I am having exams, will raise a PR till 26th
