### ISSUE TITLE
Input field number for (iitmain.py) is not matching

### ISSUE THREAD

**Issue by abhirajadhikary06** [Sohammhatre10/Cadmi_AI#8]
@Sohammhatre10 
I would like to bring this issue to your attention. I would like to fix this issue.
![image](https://github.com/user-attachments/assets/b802b85f-2e19-49ff-bbcf-88ddba3267b1)

⭐Please assign this issue to me.
Add hacktoberfest label

**Comment by Sohammhatre10** [comment]
@abhirajadhikary06 I had created the scripts `iitmain.py` and `csab.py` for the 2023-24 academic year and the fields and the HTML tags might be modified from the JOSAA and CSAB side. Will assign this to you for updating the code. All the best!

**Comment by abhirajadhikary06** [comment]
Thank you for assigning.

**Comment by Sohammhatre10** [comment]
@abhirajadhikary06 would love to keep this organised so will be closing this issue and assigning you https://github.com/Sohammhatre10/Cadmi_AI/issues/7 as its catering to the same issue.

**Comment by abhirajadhikary06** [comment]
Ok. No problem
